# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "etude-ensure"
version = "0.1.1"
description = "Small, dependency-free control-flow macros (ensure! / assume!)"
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["macro", "control-flow", "ensure", "assume", "no-std"]
categories = ["rust-patterns", "no-std"]

[dependencies]
